// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// SECDED decoder generated by util/design/secded_gen.py

module prim_secded_inv_39_32_dec (
  input        [38:0] data_i,
  output logic [31:0] data_o,
  output logic [6:0] syndrome_o,
  output logic [1:0] err_o
);

  assign data_o[31:0] = data_i[31:0];
  assign syndrome_o[6:0] = 0;
  assign err_o[1:0] = 0;

endmodule : prim_secded_inv_39_32_dec
